name: AVHC Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: cd ${GITHUB_WORKSPACE}/build && yarn
      - run: cd ${GITHUB_WORKSPACE}/functions && yarn
      - run: cd ${GITHUB_WORKSPACE}/public && yarn
