name: AVHC Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - run: cd ${GITHUB_WORKSPACE}/functions && yarn
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: cd ${GITHUB_WORKSPACE}/build && yarn
      - run: cd ${GITHUB_WORKSPACE}/public && yarn
      - run: yarn build:avhc
      - run: cd ${GITHUB_WORKSPACE}
